import { Plugin, Notice, TFile } from 'obsidian';
import { DEFAULT_SETTINGS, MyPluginSettings } from './types';
import { ZoteroSettingTab } from './settings';
import { HighlightModal } from './ui/highlights';
import { InputModal } from './ui/inputs';
import { AssistantView } from './ui/assistant';
import { WebhookService } from './services/webhook';
import { ZoteroService } from './services/zotero';
import { ObsidianService } from './services/obsidian';

export default class ZoteroGKPlugin extends Plugin {
	settings!: MyPluginSettings;
	zotero!: ZoteroService;
	obsidian!: ObsidianService;
	webhookService!: WebhookService;

	async onload() {
		await this.loadSettings();

		// Initialize Services
		this.zotero = new ZoteroService(this.settings.zoteroPort);
		this.obsidian = new ObsidianService(this.app, this.settings);
		this.webhookService = new WebhookService(this.app, this.settings);

		// 1. Register Code Block: ```zotero-assistant```
		// This processes the JSON map generated by your Zotero Integration template
		this.registerMarkdownCodeBlockProcessor("zotero-assistant", (source, el, ctx) => {
			// Pass the container element 'el' to the view
			const view = new AssistantView(el, this);

			// Register lifecycle management (required for button events)
			ctx.addChild(view);

			// Render the view using the 'source' (which is the JSON content of the block)
			view.render(source, ctx);
		});

		// 2. Manual Command (Create Literature Note)
		this.addCommand({
			id: 'zotero-create-dashboard',
			name: 'Create Literature Note (Enter Citation Key)',
			callback: () => {
				new InputModal(this.app, async (key) => {
					if (!key) return;
					try {
						const meta = await this.zotero.getItemMetadata(key);
						if(meta) {
							const file = await this.obsidian.createLiteratureNote(meta);
							await this.app.workspace.getLeaf(true).openFile(file);
						}
					} catch(e) { new Notice("Error: " + e.message); }
				}).open();
			}
		});

		// 3. Review Command (Active Note)
		this.addCommand({
			id: 'zotero-review-current',
			name: 'Review Highlights (Current Note)',
			checkCallback: (checking: boolean) => {
				const file = this.app.workspace.getActiveFile();
				if (!file) return false;
				if (!checking) this.triggerReviewForActiveFile(file);
				return true;
			}
		});

		this.addSettingTab(new ZoteroSettingTab(this.app, this));
	}

	async triggerReviewForActiveFile(file: TFile) {
		const cache = this.app.metadataCache.getFileCache(file);
		const key = cache?.frontmatter?.['zotero-key'] || cache?.frontmatter?.['citation-key'];

		// Note: For command-triggered review, we don't have the JSON map from the code block.
		// We pass an empty map, so it will rely on the fallback image finder.
		if (key) {
			new HighlightModal(this.app, this.settings, key, {}).open();
		} else {
			new Notice("❌ No citation key found.");
		}
	}

	async loadSettings() {
		this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
	}

	async saveSettings() {
		await this.saveData(this.settings);
	}
}
